[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solanadapp = "9KwYWcLzG1DjzXmXhtETDUPFKrRX2GfoKeqeF6UshktU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/fave/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
